// qae_inference_hls.cpp
//
// Fixed-point HLS implementation of QAE inference for FPGA deployment.
// Uses ap_fixed types for Vivado HLS / Vitis HLS.
//
// Bit widths chosen for balance of accuracy vs. resource usage:
// - Angles/trig values: 16 bits (2 integer, 14 fractional)
// - Statevector amplitudes: 18 bits (2 integer, 16 fractional)
// - Accumulator for measurements: 24 bits (4 integer, 20 fractional)

#include <ap_fixed.h>
#include <hls_stream.h>

// ========================== Type definitions ==========================

// Fixed-point types
typedef ap_fixed<16, 2, AP_RND, AP_SAT> angle_t;      // For angles, cos/sin values [-1, 1] or [-pi, pi]
typedef ap_fixed<18, 2, AP_RND, AP_SAT> amp_t;        // Statevector amplitudes (real/imag)
typedef ap_fixed<24, 4, AP_RND, AP_SAT> acc_t;        // Accumulators for measurements
typedef ap_fixed<20, 4, AP_RND, AP_SAT> score_t;      // Block scores and anomaly score
typedef ap_fixed<16, 8, AP_RND, AP_SAT> input_t;      // Input features (pt, eta, phi)

// Complex amplitude
struct cx_t {
    amp_t re;
    amp_t im;
};

// ========================== LUT configuration ==========================
#define TRIG_LUT_BITS 10
#define TRIG_LUT_SIZE (1 << TRIG_LUT_BITS)

// These would be generated by input_lut.py with fixed-point output
// For now, declare as extern - generate with modified script
extern const angle_t eta_phi_lut_cos[TRIG_LUT_SIZE];
extern const angle_t eta_phi_lut_sin[TRIG_LUT_SIZE];
extern const angle_t pt_lut_cos[TRIG_LUT_SIZE];
extern const angle_t pt_lut_sin[TRIG_LUT_SIZE];

// Trainable weights (cos/sin precomputed)
extern const angle_t met_weights_c[1];
extern const angle_t met_weights_s[1];
extern const angle_t ele_weights_c[4];
extern const angle_t ele_weights_s[4];
extern const angle_t mu_weights_c[4];
extern const angle_t mu_weights_s[4];
extern const angle_t jet_weights_c[40];
extern const angle_t jet_weights_s[40];

// Mahalanobis parameters
extern const score_t MAHA_MU[4];
extern const score_t MAHA_PREC[4][4];

// ========================== LUT indexing ==========================

inline int lut_index_eta_phi(input_t theta) {
    #pragma HLS INLINE
    const input_t lo = -3.14159265;
    const input_t hi = 3.14159265;
    input_t t = theta;
    if (t < lo) t = lo;
    if (t > hi) t = hi;
    input_t u = (t - lo) / (hi - lo);
    int idx = (int)(u * (TRIG_LUT_SIZE - 1));
    if (idx < 0) idx = 0;
    if (idx >= TRIG_LUT_SIZE) idx = TRIG_LUT_SIZE - 1;
    return idx;
}

inline int lut_index_pt(input_t theta) {
    #pragma HLS INLINE
    const input_t lo = 0.0;
    const input_t hi = 3.14159265;
    input_t t = theta;
    if (t < lo) t = lo;
    if (t > hi) t = hi;
    input_t u = (t - lo) / (hi - lo);
    int idx = (int)(u * (TRIG_LUT_SIZE - 1));
    if (idx < 0) idx = 0;
    if (idx >= TRIG_LUT_SIZE) idx = TRIG_LUT_SIZE - 1;
    return idx;
}

// ========================== Gate operations ==========================

// RX gate: |0> -> c|0> - is|1>, |1> -> -is|0> + c|1>
template<int NQ>
void apply_rx(cx_t sv[1 << NQ], int wire, angle_t c, angle_t s) {
    #pragma HLS INLINE off
    const int stride = 1 << wire;
    const int DIM = 1 << NQ;
    
    APPLY_RX_LOOP:
    for (int base = 0; base < DIM; base += (stride << 1)) {
        #pragma HLS PIPELINE II=1
        for (int j = 0; j < stride; ++j) {
            #pragma HLS UNROLL factor=4
            int i0 = base + j;
            int i1 = i0 + stride;
            
            cx_t a = sv[i0];
            cx_t b = sv[i1];
            
            // a' = c*a + (-i*s)*b = (c*a.re + s*b.im, c*a.im - s*b.re)
            // b' = (-i*s)*a + c*b = (s*a.im + c*b.re, -s*a.re + c*b.im)
            cx_t ap, bp;
            ap.re = c * a.re + s * b.im;
            ap.im = c * a.im - s * b.re;
            bp.re = s * a.im + c * b.re;
            bp.im = -s * a.re + c * b.im;
            
            sv[i0] = ap;
            sv[i1] = bp;
        }
    }
}

// RY gate: |0> -> c|0> + s|1>, |1> -> -s|0> + c|1>
template<int NQ>
void apply_ry(cx_t sv[1 << NQ], int wire, angle_t c, angle_t s) {
    #pragma HLS INLINE off
    const int stride = 1 << wire;
    const int DIM = 1 << NQ;
    
    APPLY_RY_LOOP:
    for (int base = 0; base < DIM; base += (stride << 1)) {
        #pragma HLS PIPELINE II=1
        for (int j = 0; j < stride; ++j) {
            #pragma HLS UNROLL factor=4
            int i0 = base + j;
            int i1 = i0 + stride;
            
            cx_t a = sv[i0];
            cx_t b = sv[i1];
            
            cx_t ap, bp;
            ap.re = c * a.re - s * b.re;
            ap.im = c * a.im - s * b.im;
            bp.re = s * a.re + c * b.re;
            bp.im = s * a.im + c * b.im;
            
            sv[i0] = ap;
            sv[i1] = bp;
        }
    }
}

// RZ gate: |0> -> e^{-i*theta/2}|0>, |1> -> e^{+i*theta/2}|1>
template<int NQ>
void apply_rz(cx_t sv[1 << NQ], int wire, angle_t c, angle_t s) {
    #pragma HLS INLINE off
    const int DIM = 1 << NQ;
    const int bit = 1 << wire;
    
    APPLY_RZ_LOOP:
    for (int i = 0; i < DIM; ++i) {
        #pragma HLS PIPELINE II=1
        cx_t a = sv[i];
        cx_t ap;
        
        if ((i & bit) == 0) {
            // e^{-i*theta/2} = c - is
            ap.re = c * a.re + s * a.im;
            ap.im = -s * a.re + c * a.im;
        } else {
            // e^{+i*theta/2} = c + is
            ap.re = c * a.re - s * a.im;
            ap.im = s * a.re + c * a.im;
        }
        sv[i] = ap;
    }
}

// CNOT gate
template<int NQ>
void apply_cnot(cx_t sv[1 << NQ], int control, int target) {
    #pragma HLS INLINE off
    const int DIM = 1 << NQ;
    const int cb = 1 << control;
    const int tb = 1 << target;
    
    APPLY_CNOT_LOOP:
    for (int i = 0; i < DIM; ++i) {
        #pragma HLS PIPELINE II=1
        if ((i & cb) && ((i & tb) == 0)) {
            int j = i | tb;
            cx_t tmp = sv[i];
            sv[i] = sv[j];
            sv[j] = tmp;
        }
    }
}

// ========================== Measurement ==========================

template<int NQ>
acc_t measure_expZ(const cx_t sv[1 << NQ], int wire) {
    #pragma HLS INLINE off
    const int DIM = 1 << NQ;
    const int bit = 1 << wire;
    acc_t acc = 0;
    
    MEASURE_LOOP:
    for (int i = 0; i < DIM; ++i) {
        #pragma HLS PIPELINE II=1
        acc_t p = sv[i].re * sv[i].re + sv[i].im * sv[i].im;
        if (i & bit) {
            acc -= p;
        } else {
            acc += p;
        }
    }
    return acc;
}

// ========================== Block circuits ==========================

// MET block: 1 qubit
score_t run_met_block(input_t pt, input_t phi) {
    #pragma HLS INLINE off
    #pragma HLS DATAFLOW
    
    cx_t sv[2];
    #pragma HLS ARRAY_PARTITION variable=sv complete
    
    // Initialize |0>
    sv[0].re = 1; sv[0].im = 0;
    sv[1].re = 0; sv[1].im = 0;
    
    // RY(pt)
    int pt_idx = lut_index_pt(pt);
    apply_ry<1>(sv, 0, pt_lut_cos[pt_idx], pt_lut_sin[pt_idx]);
    
    // RZ(phi)
    int phi_idx = lut_index_eta_phi(phi);
    apply_rz<1>(sv, 0, eta_phi_lut_cos[phi_idx], eta_phi_lut_sin[phi_idx]);
    
    // Trainable RY
    apply_ry<1>(sv, 0, met_weights_c[0], met_weights_s[0]);
    
    // Measure and compute trash excitation
    acc_t z = measure_expZ<1>(sv, 0);
    score_t excitation = (score_t)0.5 * ((score_t)1.0 - (score_t)z);
    
    return excitation;
}

// Electron block: 4 qubits, trash=[2,3]
score_t run_ele_block(input_t pt[4], input_t eta[4], input_t phi[4]) {
    #pragma HLS INLINE off
    #pragma HLS ARRAY_PARTITION variable=pt complete
    #pragma HLS ARRAY_PARTITION variable=eta complete
    #pragma HLS ARRAY_PARTITION variable=phi complete
    
    cx_t sv[16];
    #pragma HLS ARRAY_PARTITION variable=sv cyclic factor=4
    
    // Initialize |0000>
    INIT_ELE:
    for (int i = 0; i < 16; ++i) {
        #pragma HLS UNROLL
        sv[i].re = (i == 0) ? (amp_t)1 : (amp_t)0;
        sv[i].im = 0;
    }
    
    // Feature encoding
    ENCODE_ELE:
    for (int k = 0; k < 4; ++k) {
        int eta_idx = lut_index_eta_phi(eta[k]);
        int pt_idx = lut_index_pt(pt[k]);
        int phi_idx = lut_index_eta_phi(phi[k]);
        
        apply_rx<4>(sv, k, eta_phi_lut_cos[eta_idx], eta_phi_lut_sin[eta_idx]);
        apply_ry<4>(sv, k, pt_lut_cos[pt_idx], pt_lut_sin[pt_idx]);
        apply_rz<4>(sv, k, eta_phi_lut_cos[phi_idx], eta_phi_lut_sin[phi_idx]);
    }
    
    // Ansatz: depth=1
    // trash -> latent CNOTs
    const int latent[2] = {0, 1};
    const int trash[2] = {2, 3};
    
    for (int ti = 0; ti < 2; ++ti) {
        for (int li = 0; li < 2; ++li) {
            apply_cnot<4>(sv, trash[ti], latent[li]);
        }
    }
    
    // Trainable RY
    for (int k = 0; k < 4; ++k) {
        apply_ry<4>(sv, k, ele_weights_c[k], ele_weights_s[k]);
    }
    
    // latent -> trash CNOTs
    for (int li = 0; li < 2; ++li) {
        for (int ti = 0; ti < 2; ++ti) {
            apply_cnot<4>(sv, latent[li], trash[ti]);
        }
    }
    
    // Measure trash qubits
    acc_t z2 = measure_expZ<4>(sv, 2);
    acc_t z3 = measure_expZ<4>(sv, 3);
    
    score_t exc2 = (score_t)0.5 * ((score_t)1.0 - (score_t)z2);
    score_t exc3 = (score_t)0.5 * ((score_t)1.0 - (score_t)z3);
    
    return (exc2 + exc3) * (score_t)0.5;
}

// Muon block: 4 qubits, trash=[2,3] (same structure as electron)
score_t run_mu_block(input_t pt[4], input_t eta[4], input_t phi[4]) {
    #pragma HLS INLINE off
    #pragma HLS ARRAY_PARTITION variable=pt complete
    #pragma HLS ARRAY_PARTITION variable=eta complete
    #pragma HLS ARRAY_PARTITION variable=phi complete
    
    cx_t sv[16];
    #pragma HLS ARRAY_PARTITION variable=sv cyclic factor=4
    
    INIT_MU:
    for (int i = 0; i < 16; ++i) {
        #pragma HLS UNROLL
        sv[i].re = (i == 0) ? (amp_t)1 : (amp_t)0;
        sv[i].im = 0;
    }
    
    ENCODE_MU:
    for (int k = 0; k < 4; ++k) {
        int eta_idx = lut_index_eta_phi(eta[k]);
        int pt_idx = lut_index_pt(pt[k]);
        int phi_idx = lut_index_eta_phi(phi[k]);
        
        apply_rx<4>(sv, k, eta_phi_lut_cos[eta_idx], eta_phi_lut_sin[eta_idx]);
        apply_ry<4>(sv, k, pt_lut_cos[pt_idx], pt_lut_sin[pt_idx]);
        apply_rz<4>(sv, k, eta_phi_lut_cos[phi_idx], eta_phi_lut_sin[phi_idx]);
    }
    
    const int latent[2] = {0, 1};
    const int trash[2] = {2, 3};
    
    for (int ti = 0; ti < 2; ++ti) {
        for (int li = 0; li < 2; ++li) {
            apply_cnot<4>(sv, trash[ti], latent[li]);
        }
    }
    
    for (int k = 0; k < 4; ++k) {
        apply_ry<4>(sv, k, mu_weights_c[k], mu_weights_s[k]);
    }
    
    for (int li = 0; li < 2; ++li) {
        for (int ti = 0; ti < 2; ++ti) {
            apply_cnot<4>(sv, latent[li], trash[ti]);
        }
    }
    
    acc_t z2 = measure_expZ<4>(sv, 2);
    acc_t z3 = measure_expZ<4>(sv, 3);
    
    score_t exc2 = (score_t)0.5 * ((score_t)1.0 - (score_t)z2);
    score_t exc3 = (score_t)0.5 * ((score_t)1.0 - (score_t)z3);
    
    return (exc2 + exc3) * (score_t)0.5;
}

// Jet block: 10 qubits, trash=[6,7,8,9], depth=4
score_t run_jet_block(input_t pt[10], input_t eta[10], input_t phi[10]) {
    #pragma HLS INLINE off
    #pragma HLS ARRAY_PARTITION variable=pt complete
    #pragma HLS ARRAY_PARTITION variable=eta complete
    #pragma HLS ARRAY_PARTITION variable=phi complete
    
    cx_t sv[1024];
    #pragma HLS ARRAY_PARTITION variable=sv cyclic factor=16
    #pragma HLS RESOURCE variable=sv core=RAM_2P_BRAM
    
    // Initialize |0000000000>
    INIT_JET:
    for (int i = 0; i < 1024; ++i) {
        #pragma HLS PIPELINE II=1
        sv[i].re = (i == 0) ? (amp_t)1 : (amp_t)0;
        sv[i].im = 0;
    }
    
    // Feature encoding
    ENCODE_JET:
    for (int k = 0; k < 10; ++k) {
        int eta_idx = lut_index_eta_phi(eta[k]);
        int pt_idx = lut_index_pt(pt[k]);
        int phi_idx = lut_index_eta_phi(phi[k]);
        
        apply_rx<10>(sv, k, eta_phi_lut_cos[eta_idx], eta_phi_lut_sin[eta_idx]);
        apply_ry<10>(sv, k, pt_lut_cos[pt_idx], pt_lut_sin[pt_idx]);
        apply_rz<10>(sv, k, eta_phi_lut_cos[phi_idx], eta_phi_lut_sin[phi_idx]);
    }
    
    const int latent[6] = {0, 1, 2, 3, 4, 5};
    const int trash[4] = {6, 7, 8, 9};
    
    // Ansatz: depth=4
    ANSATZ_JET:
    for (int d = 0; d < 4; ++d) {
        // trash -> latent CNOTs
        for (int ti = 0; ti < 4; ++ti) {
            for (int li = 0; li < 6; ++li) {
                apply_cnot<10>(sv, trash[ti], latent[li]);
            }
        }
        
        // Trainable RY
        int base = d * 10;
        for (int k = 0; k < 10; ++k) {
            apply_ry<10>(sv, k, jet_weights_c[base + k], jet_weights_s[base + k]);
        }
        
        // latent -> trash CNOTs
        for (int li = 0; li < 6; ++li) {
            for (int ti = 0; ti < 4; ++ti) {
                apply_cnot<10>(sv, latent[li], trash[ti]);
            }
        }
    }
    
    // Measure trash qubits
    acc_t z6 = measure_expZ<10>(sv, 6);
    acc_t z7 = measure_expZ<10>(sv, 7);
    acc_t z8 = measure_expZ<10>(sv, 8);
    acc_t z9 = measure_expZ<10>(sv, 9);
    
    score_t exc6 = (score_t)0.5 * ((score_t)1.0 - (score_t)z6);
    score_t exc7 = (score_t)0.5 * ((score_t)1.0 - (score_t)z7);
    score_t exc8 = (score_t)0.5 * ((score_t)1.0 - (score_t)z8);
    score_t exc9 = (score_t)0.5 * ((score_t)1.0 - (score_t)z9);
    
    return (exc6 + exc7 + exc8 + exc9) * (score_t)0.25;
}

// ========================== Mahalanobis scoring ==========================

score_t mahalanobis_score(score_t s[4]) {
    #pragma HLS INLINE off
    #pragma HLS ARRAY_PARTITION variable=s complete
    
    score_t d[4];
    #pragma HLS ARRAY_PARTITION variable=d complete
    
    for (int i = 0; i < 4; ++i) {
        #pragma HLS UNROLL
        d[i] = s[i] - MAHA_MU[i];
    }
    
    score_t q = 0;
    for (int i = 0; i < 4; ++i) {
        #pragma HLS UNROLL
        score_t row = 0;
        for (int j = 0; j < 4; ++j) {
            #pragma HLS UNROLL
            row += MAHA_PREC[i][j] * d[j];
        }
        q += d[i] * row;
    }
    
    return q * (score_t)0.5;
}

// ========================== Top-level function ==========================

// Input: 56 features packed as input_t array
// Output: anomaly score
void qae_inference_top(
    input_t features[56],
    score_t* anomaly_score
) {
    #pragma HLS INTERFACE s_axilite port=features
    #pragma HLS INTERFACE s_axilite port=anomaly_score
    #pragma HLS INTERFACE s_axilite port=return
    
    #pragma HLS ARRAY_PARTITION variable=features complete
    
    // Extract features for each block
    // MET: pt=0, phi=1
    input_t met_pt = features[0];
    input_t met_phi = features[1];
    
    // Electrons: pt[2:6], eta[6:10], phi[10:14]
    input_t ele_pt[4], ele_eta[4], ele_phi[4];
    #pragma HLS ARRAY_PARTITION variable=ele_pt complete
    #pragma HLS ARRAY_PARTITION variable=ele_eta complete
    #pragma HLS ARRAY_PARTITION variable=ele_phi complete
    for (int k = 0; k < 4; ++k) {
        #pragma HLS UNROLL
        ele_pt[k] = features[2 + k];
        ele_eta[k] = features[6 + k];
        ele_phi[k] = features[10 + k];
    }
    
    // Muons: pt[14:18], eta[18:22], phi[22:26]
    input_t mu_pt[4], mu_eta[4], mu_phi[4];
    #pragma HLS ARRAY_PARTITION variable=mu_pt complete
    #pragma HLS ARRAY_PARTITION variable=mu_eta complete
    #pragma HLS ARRAY_PARTITION variable=mu_phi complete
    for (int k = 0; k < 4; ++k) {
        #pragma HLS UNROLL
        mu_pt[k] = features[14 + k];
        mu_eta[k] = features[18 + k];
        mu_phi[k] = features[22 + k];
    }
    
    // Jets: pt[26:36], eta[36:46], phi[46:56]
    input_t jet_pt[10], jet_eta[10], jet_phi[10];
    #pragma HLS ARRAY_PARTITION variable=jet_pt complete
    #pragma HLS ARRAY_PARTITION variable=jet_eta complete
    #pragma HLS ARRAY_PARTITION variable=jet_phi complete
    for (int k = 0; k < 10; ++k) {
        #pragma HLS UNROLL
        jet_pt[k] = features[26 + k];
        jet_eta[k] = features[36 + k];
        jet_phi[k] = features[46 + k];
    }
    
    // Run blocks (can be parallelized with DATAFLOW)
    #pragma HLS DATAFLOW
    score_t met_score = run_met_block(met_pt, met_phi);
    score_t ele_score = run_ele_block(ele_pt, ele_eta, ele_phi);
    score_t mu_score = run_mu_block(mu_pt, mu_eta, mu_phi);
    score_t jet_score = run_jet_block(jet_pt, jet_eta, jet_phi);
    
    // Compute Mahalanobis score
    score_t block_scores[4] = {met_score, ele_score, mu_score, jet_score};
    *anomaly_score = mahalanobis_score(block_scores);
}
