#!/usr/bin/env python3
# weights_exporter.py
#
# Export trained QAE weights and Mahalanobis stats to C++ headers for HLS/FPGA deployment.
#
# Usage:
#   python weights_exporter.py --ckpt path/to/model.pt --out-weights qae_weights.h --out-maha mahalanobis.h

import argparse
import math
from pathlib import Path
from typing import Dict, Any

import torch


def _to_list(t: torch.Tensor):
    return t.detach().cpu().double().flatten().tolist()


def _emit_array(f, ctype: str, name: str, values, per_line: int = 4):
    f.write(f"static const {ctype} {name}[{len(values)}] = {{\n")
    for i, v in enumerate(values):
        if i % per_line == 0:
            f.write("    ")
        f.write(f"{v:.18e}")
        if i != len(values) - 1:
            f.write(", ")
        if (i % per_line == per_line - 1) or (i == len(values) - 1):
            f.write("\n")
    f.write("};\n\n")


def _emit_2d_array(f, ctype: str, name: str, values_2d, per_line: int = 4):
    """Emit a 2D array for C++."""
    rows = len(values_2d)
    cols = len(values_2d[0]) if rows > 0 else 0
    f.write(f"static const {ctype} {name}[{rows}][{cols}] = {{\n")
    for i, row in enumerate(values_2d):
        f.write("    {")
        for j, v in enumerate(row):
            f.write(f"{v:.18e}")
            if j != len(row) - 1:
                f.write(", ")
        f.write("}")
        if i != rows - 1:
            f.write(",")
        f.write("\n")
    f.write("};\n\n")


def _emit_cs_arrays(f, base_name: str, angles):
    """Emit cos(theta/2) and sin(theta/2) arrays for rotation gates."""
    c_vals = [math.cos(0.5 * a) for a in angles]
    s_vals = [math.sin(0.5 * a) for a in angles]
    _emit_array(f, "double", f"{base_name}_c", c_vals)
    _emit_array(f, "double", f"{base_name}_s", s_vals)


def _extract_state_dict(ckpt_obj: Any) -> Dict[str, torch.Tensor]:
    """
    Supports:
      - raw state_dict
      - {'state_dict': ...}
      - {'model_state_dict': ...}
    """
    if isinstance(ckpt_obj, dict):
        if "state_dict" in ckpt_obj and isinstance(ckpt_obj["state_dict"], dict):
            return ckpt_obj["state_dict"]
        if "model_state_dict" in ckpt_obj and isinstance(ckpt_obj["model_state_dict"], dict):
            return ckpt_obj["model_state_dict"]
        if all(isinstance(v, torch.Tensor) for v in ckpt_obj.values()):
            return ckpt_obj
    raise ValueError("Could not interpret checkpoint format as a PyTorch state_dict.")


def export_weights(ckpt_path: Path, out_path: Path):
    """Export trainable weights to C++ header."""
    ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=False)
    sd = _extract_state_dict(ckpt)

    # Keys for the QAE encoder weights
    candidate_keys = {
        "met_weights": ["encoder.met_weights", "met_weights"],
        "ele_weights": ["encoder.ele_weights", "ele_weights"],
        "mu_weights":  ["encoder.mu_weights",  "mu_weights"],
        "jet_weights": ["encoder.jet_weights", "jet_weights"],
    }

    extracted = {}
    for logical_name, keys in candidate_keys.items():
        found = None
        for k in keys:
            if k in sd:
                found = sd[k]
                break
        if found is None:
            raise KeyError(f"Could not find {logical_name}. Tried keys: {keys}")
        extracted[logical_name] = _to_list(found)

    with open(out_path, "w") as f:
        f.write("// Auto-generated by weights_exporter.py\n")
        f.write("// Trainable RY angles and precomputed cos/sin(theta/2) for HLS\n\n")
        f.write("#pragma once\n\n")

        # Raw trainable angles (useful for debug)
        for name in ["met_weights", "ele_weights", "mu_weights", "jet_weights"]:
            _emit_array(f, "double", name, extracted[name])

        # Precomputed c/s values for rotation gates
        for name in ["met_weights", "ele_weights", "mu_weights", "jet_weights"]:
            _emit_cs_arrays(f, name, extracted[name])

        # Metadata constants
        f.write(f"static const int MET_W_COUNT = {len(extracted['met_weights'])};\n")
        f.write(f"static const int ELE_W_COUNT = {len(extracted['ele_weights'])};\n")
        f.write(f"static const int MU_W_COUNT  = {len(extracted['mu_weights'])};\n")
        f.write(f"static const int JET_W_COUNT = {len(extracted['jet_weights'])};\n\n")

    print(f"Wrote weights to {out_path}")


def export_mahalanobis(ckpt_path: Path, out_path: Path):
    """Export Mahalanobis stats (mu, precision) to C++ header."""
    ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=False)
    
    # Try to get mu and precision from checkpoint
    mu = None
    precision = None
    
    # Check top-level keys first
    if 'bg_mu' in ckpt:
        mu = _to_list(ckpt['bg_mu'])
    if 'bg_precision' in ckpt:
        precision = ckpt['bg_precision'].detach().cpu().double().tolist()
    
    # Also check state_dict
    if mu is None or precision is None:
        sd = _extract_state_dict(ckpt)
        if mu is None:
            for k in ['mu', 'encoder.mu']:
                if k in sd:
                    mu = _to_list(sd[k])
                    break
        if precision is None:
            for k in ['precision', 'encoder.precision']:
                if k in sd:
                    precision = sd[k].detach().cpu().double().tolist()
                    break
    
    if mu is None:
        print("Warning: Could not find mu in checkpoint. Using zeros.")
        mu = [0.0, 0.0, 0.0, 0.0]
    if precision is None:
        print("Warning: Could not find precision in checkpoint. Using identity.")
        precision = [[1.0, 0.0, 0.0, 0.0],
                     [0.0, 1.0, 0.0, 0.0],
                     [0.0, 0.0, 1.0, 0.0],
                     [0.0, 0.0, 0.0, 1.0]]

    with open(out_path, "w") as f:
        f.write("// Auto-generated by weights_exporter.py\n")
        f.write("// Mahalanobis scoring constants\n\n")
        f.write("#pragma once\n\n")
        
        _emit_array(f, "double", "MAHA_MU", mu)
        _emit_2d_array(f, "double", "MAHA_PREC", precision)

    print(f"Wrote Mahalanobis stats to {out_path}")


def main():
    ap = argparse.ArgumentParser(description="Export QAE weights and stats to C++ headers")
    ap.add_argument("--ckpt", required=True, help="Path to .pt checkpoint")
    ap.add_argument("--out-weights", default="qae_weights.h", help="Output weights header")
    ap.add_argument("--out-maha", default="mahalanobis.h", help="Output Mahalanobis header")
    ap.add_argument("--out-dir", default=".", help="Output directory for headers")
    args = ap.parse_args()

    ckpt_path = Path(args.ckpt)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    
    export_weights(ckpt_path, out_dir / args.out_weights)
    export_mahalanobis(ckpt_path, out_dir / args.out_maha)
    
    print("\nDone! Now generate trig LUTs with:")
    print(f"  python input_lut.py --out {out_dir}/trig_luts.h --nbits 10")
    print("\nThen compile the C++ inference:")
    print(f"  g++ -O3 -std=c++17 -I{out_dir} -o qae_inference qae_inference_ref.cpp")


if __name__ == "__main__":
    main()
