#!/usr/bin/env python3
"""
Export extended_quantum_vae.py weights to C++ headers.

Generates:
  - extended_vae_weights.h: Trainable weights with precomputed cos/sin
  - trig_luts.h: Trigonometric lookup tables
"""

import argparse
import math
from pathlib import Path
import torch


def _to_list(t):
    return t.detach().cpu().double().flatten().tolist()


def _emit_array(f, ctype, name, values, per_line=4):
    f.write(f"static const {ctype} {name}[{len(values)}] = {{\n")
    for i, v in enumerate(values):
        if i % per_line == 0:
            f.write("    ")
        f.write(f"{v:.18e}")
        if i != len(values) - 1:
            f.write(", ")
        if (i % per_line == per_line - 1) or (i == len(values) - 1):
            f.write("\n")
    f.write("};\n\n")


def _emit_cs_arrays(f, base_name, angles):
    """Emit cos(theta/2) and sin(theta/2) arrays."""
    c_vals = [math.cos(0.5 * a) for a in angles]
    s_vals = [math.sin(0.5 * a) for a in angles]
    _emit_array(f, "double", f"{base_name}_c", c_vals)
    _emit_array(f, "double", f"{base_name}_s", s_vals)


def export_weights(ckpt_path, out_path, depth=2):
    """Export extended VAE encoder weights."""
    ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=False)
    
    # Extract state dict
    if "model_state_dict" in ckpt:
        sd = ckpt["model_state_dict"]
    elif "state_dict" in ckpt:
        sd = ckpt["state_dict"]
    else:
        sd = ckpt

    # Find weights with various possible key prefixes
    def get_weights(keys):
        for k in keys:
            if k in sd:
                return _to_list(sd[k])
        raise KeyError(f"Could not find any of {keys}")

    met_w = get_weights(["encoder.met_weights", "met_weights"])
    ele_w = get_weights(["encoder.ele_weights", "ele_weights"])
    mu_w = get_weights(["encoder.mu_weights", "mu_weights"])
    jet_w = get_weights(["encoder.jet_weights", "jet_weights"])

    # Infer depth from weight sizes
    met_depth = len(met_w) // 3
    ele_depth = len(ele_w) // 8
    mu_depth = len(mu_w) // 8
    jet_depth = len(jet_w) // 13

    with open(out_path, "w") as f:
        f.write("// Auto-generated by export_extended_vae_weights.py\n")
        f.write("// Extended Quantum VAE encoder weights\n\n")
        f.write("#pragma once\n\n")

        # Depth constants
        f.write(f"static const int MET_DEPTH = {met_depth};\n")
        f.write(f"static const int ELE_DEPTH = {ele_depth};\n")
        f.write(f"static const int MU_DEPTH = {mu_depth};\n")
        f.write(f"static const int JET_DEPTH = {jet_depth};\n\n")

        # Raw weights
        _emit_array(f, "double", "met_weights", met_w)
        _emit_array(f, "double", "ele_weights", ele_w)
        _emit_array(f, "double", "mu_weights", mu_w)
        _emit_array(f, "double", "jet_weights", jet_w)

        # Precomputed cos/sin
        _emit_cs_arrays(f, "met_weights", met_w)
        _emit_cs_arrays(f, "ele_weights", ele_w)
        _emit_cs_arrays(f, "mu_weights", mu_w)
        _emit_cs_arrays(f, "jet_weights", jet_w)

    print(f"Wrote {out_path}")
    print(f"  MET depth: {met_depth}, weights: {len(met_w)}")
    print(f"  ELE depth: {ele_depth}, weights: {len(ele_w)}")
    print(f"  MU depth: {mu_depth}, weights: {len(mu_w)}")
    print(f"  JET depth: {jet_depth}, weights: {len(jet_w)}")


def export_trig_luts(out_path, nbits=10):
    """Generate trig LUTs."""
    n = 1 << nbits

    eta_phi_c, eta_phi_s = [], []
    for i in range(n):
        t = -math.pi + (i + 0.5) * (2 * math.pi) / n
        eta_phi_c.append(math.cos(0.5 * t))
        eta_phi_s.append(math.sin(0.5 * t))

    pt_c, pt_s = [], []
    for i in range(n):
        t = (i + 0.5) * math.pi / n
        pt_c.append(math.cos(0.5 * t))
        pt_s.append(math.sin(0.5 * t))

    with open(out_path, "w") as f:
        f.write("// Auto-generated trig LUTs\n\n")
        f.write("#pragma once\n\n")
        f.write(f"static const int TRIG_LUT_NBITS = {nbits};\n")
        f.write(f"static const int TRIG_LUT_SIZE = {n};\n\n")

        _emit_array(f, "double", "eta_phi_lut_cos", eta_phi_c)
        _emit_array(f, "double", "eta_phi_lut_sin", eta_phi_s)
        _emit_array(f, "double", "pt_lut_cos", pt_c)
        _emit_array(f, "double", "pt_lut_sin", pt_s)

    print(f"Wrote {out_path}")


def main():
    parser = argparse.ArgumentParser(description="Export extended VAE weights for C++")
    parser.add_argument("--ckpt", required=True, help="Path to model checkpoint")
    parser.add_argument("--out-dir", default=".", help="Output directory")
    parser.add_argument("--nbits", type=int, default=10, help="LUT index bits")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    export_weights(args.ckpt, out_dir / "extended_vae_weights.h")
    export_trig_luts(out_dir / "trig_luts.h", args.nbits)

    print(f"\nDone! To compile:")
    print(f"  g++ -O3 -std=c++17 -I{out_dir} -o extended_vae_inference extended_vae_inference_ref.cpp")


if __name__ == "__main__":
    main()
