// qae_inference_ref.cpp
//
// Full C++ CPU-reference inference path for block_quantum_ae.py QAE anomaly model.
// Matches the architecture with standard particle assignments:
//
// - MET block (1 qubit): MET
// - Electrons block (4 qubits): e0, e1, e2, e3 (trash wires 2,3)
// - Muons block (4 qubits): mu0, mu1, mu2, mu3 (trash wires 2,3)
// - Jets block (10 qubits): j0-j9 (trash wires 6,7,8,9)
//
// - Encoding: RX(eta), RY(pt), RZ(phi)
// - Trainable layers: RY(weights)
// - Entangling: all-to-all CNOT between trash<->latent
// - Measurement: PauliZ on trash wires
// - Scoring: s_b = mean((1-Z)/2) per block
// - Mahalanobis score: 0.5 * (s-mu)^T Precision (s-mu)
//
// Input normalization (linear to [0,1]):
//   - pt:  pt / 1200
//   - eta: (eta + 5) / 10
//   - phi: (phi + pi) / (2*pi)
//
// Requires generated headers from Python export step:
//   - qae_weights.h   (trainable RY weights and precomputed cos/sin)
//   - mahalanobis.h   (mu[4], precision[4][4])

#include <array>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <iostream>
#include <stdexcept>

// Auto-generated by your Python exporters:
#include "qae_weights.h"
#include "mahalanobis.h"

// -------------------------- Input normalization --------------------------
// QAE was trained with linear normalization to [0,1]:
//   pt:  pt / 1200
//   eta: (eta + 5) / 10
//   phi: (phi + pi) / (2*pi)

inline double normalize_pt(double pt) {
    return pt / 1200.0;
}

inline double normalize_eta(double eta) {
    return (eta + 5.0) / 10.0;
}

inline double normalize_phi(double phi) {
    return (phi + M_PI) / (2.0 * M_PI);
}

// -------------------------- Feature index mapping --------------------------
// Input x has size 56 with layout:
// MET: pt=x[0], phi=x[1]
// Ele: pt[2:6], eta[6:10], phi[10:14]  (e0,e1,e2,e3)
// Mu:  pt[14:18], eta[18:22], phi[22:26]  (mu0,mu1,mu2,mu3)
// Jet: pt[26:36], eta[36:46], phi[46:56]  (j0-j9)

// Particle index struct: (pt_idx, eta_idx, phi_idx) - eta_idx=-1 for MET
struct ParticleIdx {
    int pt, eta, phi;
};

// Particle indices matching PARTICLE_INDICES in Python
static const ParticleIdx PARTICLE_MET  = {0, -1, 1};
static const ParticleIdx PARTICLE_E0   = {2, 6, 10};
static const ParticleIdx PARTICLE_E1   = {3, 7, 11};
static const ParticleIdx PARTICLE_E2   = {4, 8, 12};
static const ParticleIdx PARTICLE_E3   = {5, 9, 13};
static const ParticleIdx PARTICLE_MU0  = {14, 18, 22};
static const ParticleIdx PARTICLE_MU1  = {15, 19, 23};
static const ParticleIdx PARTICLE_MU2  = {16, 20, 24};
static const ParticleIdx PARTICLE_MU3  = {17, 21, 25};
static const ParticleIdx PARTICLE_J0   = {26, 36, 46};
static const ParticleIdx PARTICLE_J1   = {27, 37, 47};
static const ParticleIdx PARTICLE_J2   = {28, 38, 48};
static const ParticleIdx PARTICLE_J3   = {29, 39, 49};
static const ParticleIdx PARTICLE_J4   = {30, 40, 50};
static const ParticleIdx PARTICLE_J5   = {31, 41, 51};
static const ParticleIdx PARTICLE_J6   = {32, 42, 52};
static const ParticleIdx PARTICLE_J7   = {33, 43, 53};
static const ParticleIdx PARTICLE_J8   = {34, 44, 54};
static const ParticleIdx PARTICLE_J9   = {35, 45, 55};

// Block particle assignments (matching block_quantum_ae.py - standard layout)
// MET block: MET
static const ParticleIdx MET_BLOCK_PARTICLES[1] = {PARTICLE_MET};

// Electrons block: e0, e1, e2, e3
static const ParticleIdx ELE_BLOCK_PARTICLES[4] = {PARTICLE_E0, PARTICLE_E1, PARTICLE_E2, PARTICLE_E3};

// Muons block: mu0, mu1, mu2, mu3
static const ParticleIdx MU_BLOCK_PARTICLES[4] = {PARTICLE_MU0, PARTICLE_MU1, PARTICLE_MU2, PARTICLE_MU3};

// Jets block: j0, j1, j2, j3, j4, j5, j6, j7, j8, j9
static const ParticleIdx JET_BLOCK_PARTICLES[10] = {
    PARTICLE_J0, PARTICLE_J1, PARTICLE_J2, PARTICLE_J3, PARTICLE_J4,
    PARTICLE_J5, PARTICLE_J6, PARTICLE_J7, PARTICLE_J8, PARTICLE_J9
};

// -------------------------- Basic complex + statevector utils --------------------------
struct Cx {
    double re;
    double im;
};

inline Cx cx_add(const Cx& a, const Cx& b) { return {a.re + b.re, a.im + b.im}; }
inline Cx cx_sub(const Cx& a, const Cx& b) { return {a.re - b.re, a.im - b.im}; }
inline Cx cx_mul_real(const Cx& a, double x) { return {a.re * x, a.im * x}; }

// (-i * s) * (re + i im) = (s*im) + i(-s*re)
inline Cx cx_mul_minus_i(const Cx& a, double s) { return {s * a.im, -s * a.re}; }

// e^{+i phi} * a
inline Cx cx_mul_phase_pos(const Cx& a, double c, double s) {
    return {a.re * c - a.im * s, a.re * s + a.im * c};
}

// e^{-i phi} * a
inline Cx cx_mul_phase_neg(const Cx& a, double c, double s) {
    return {a.re * c + a.im * s, -a.re * s + a.im * c};
}

template <int NQ>
struct StateVec {
    static constexpr int DIM = 1 << NQ;
    std::array<Cx, DIM> a{};

    void init_zero() {
        for (int i = 0; i < DIM; ++i) a[i] = {0.0, 0.0};
        a[0] = {1.0, 0.0};
    }
};

// -------------------------- Trig helpers --------------------------
// Rotation gates use theta/2 internally: RX(theta) = exp(-i*theta/2 * X)
// So we compute cos(theta/2) and sin(theta/2) where theta is the normalized value

inline void get_cs(double theta, double& c, double& s) {
    double half = theta / 2.0;
    c = std::cos(half);
    s = std::sin(half);
}

// -------------------------- Gate kernels --------------------------
template <int NQ>
void apply_rx(StateVec<NQ>& sv, int wire, double c, double s) {
    const int stride = 1 << wire;
    constexpr int DIM = StateVec<NQ>::DIM;

    for (int base = 0; base < DIM; base += (stride << 1)) {
        for (int j = 0; j < stride; ++j) {
            int i0 = base + j;
            int i1 = i0 + stride;

            Cx a = sv.a[i0];
            Cx b = sv.a[i1];

            Cx ap = cx_add(cx_mul_real(a, c), cx_mul_minus_i(b, s));
            Cx bp = cx_add(cx_mul_minus_i(a, s), cx_mul_real(b, c));
            sv.a[i0] = ap;
            sv.a[i1] = bp;
        }
    }
}

template <int NQ>
void apply_ry(StateVec<NQ>& sv, int wire, double c, double s) {
    const int stride = 1 << wire;
    constexpr int DIM = StateVec<NQ>::DIM;

    for (int base = 0; base < DIM; base += (stride << 1)) {
        for (int j = 0; j < stride; ++j) {
            int i0 = base + j;
            int i1 = i0 + stride;

            Cx a = sv.a[i0];
            Cx b = sv.a[i1];

            Cx ap = cx_sub(cx_mul_real(a, c), cx_mul_real(b, s));
            Cx bp = cx_add(cx_mul_real(a, s), cx_mul_real(b, c));
            sv.a[i0] = ap;
            sv.a[i1] = bp;
        }
    }
}

template <int NQ>
void apply_rz(StateVec<NQ>& sv, int wire, double c, double s) {
    constexpr int DIM = StateVec<NQ>::DIM;
    const int bit = 1 << wire;

    for (int i = 0; i < DIM; ++i) {
        if ((i & bit) == 0) {
            sv.a[i] = cx_mul_phase_neg(sv.a[i], c, s);
        } else {
            sv.a[i] = cx_mul_phase_pos(sv.a[i], c, s);
        }
    }
}

template <int NQ>
void apply_cnot(StateVec<NQ>& sv, int control, int target) {
    if (control == target) throw std::runtime_error("CNOT control == target");
    constexpr int DIM = StateVec<NQ>::DIM;
    const int cb = 1 << control;
    const int tb = 1 << target;

    for (int i = 0; i < DIM; ++i) {
        if ((i & cb) && ((i & tb) == 0)) {
            int j = i | tb;
            std::swap(sv.a[i], sv.a[j]);
        }
    }
}

// -------------------------- Measurements --------------------------
template <int NQ>
double measure_expZ(const StateVec<NQ>& sv, int wire) {
    constexpr int DIM = StateVec<NQ>::DIM;
    const int bit = 1 << wire;
    double acc = 0.0;

    for (int i = 0; i < DIM; ++i) {
        const auto& z = sv.a[i];
        double p = z.re * z.re + z.im * z.im;
        acc += ((i & bit) ? -p : +p);
    }
    return acc;
}

// -------------------------- Block runners --------------------------

// MET block: 1 qubit, particle = MET
double run_met_block_z(const double x[56]) {
    StateVec<1> sv;
    sv.init_zero();

    const ParticleIdx& p = MET_BLOCK_PARTICLES[0];
    
    // Normalize raw inputs
    double pt_norm = normalize_pt(x[p.pt]);
    double phi_norm = normalize_phi(x[p.phi]);
    
    // qml.RY(pt, wires=0)
    {
        double c, s;
        get_cs(pt_norm, c, s);
        apply_ry(sv, 0, c, s);
    }

    // qml.RZ(phi, wires=0)
    {
        double c, s;
        get_cs(phi_norm, c, s);
        apply_rz(sv, 0, c, s);
    }

    // trainable RY(weights[0])
    apply_ry(sv, 0, met_weights_c[0], met_weights_s[0]);

    return measure_expZ(sv, 0);
}

// Electrons block: 4 qubits, particles = e0, e1, e2, e3
std::array<double, 2> run_ele_block_z(const double x[56]) {
    StateVec<4> sv;
    sv.init_zero();

    // Feature map for k=0..3
    for (int k = 0; k < 4; ++k) {
        const ParticleIdx& p = ELE_BLOCK_PARTICLES[k];
        double c, s;
        
        // Normalize raw inputs
        double pt_norm = normalize_pt(x[p.pt]);
        double eta_norm = (p.eta >= 0) ? normalize_eta(x[p.eta]) : 0.0;
        double phi_norm = normalize_phi(x[p.phi]);
        
        // RX(eta)
        get_cs(eta_norm, c, s);
        apply_rx(sv, k, c, s);
        
        // RY(pt)
        get_cs(pt_norm, c, s);
        apply_ry(sv, k, c, s);
        
        // RZ(phi)
        get_cs(phi_norm, c, s);
        apply_rz(sv, k, c, s);
    }

    // depth=1: trash -> latent all-to-all, RY(all), latent -> trash all-to-all
    const int latent[2] = {0, 1};
    const int trash[2]  = {2, 3};

    for (int ti = 0; ti < 2; ++ti) {
        for (int li = 0; li < 2; ++li) apply_cnot(sv, trash[ti], latent[li]);
    }

    for (int k = 0; k < 4; ++k) apply_ry(sv, k, ele_weights_c[k], ele_weights_s[k]);

    for (int li = 0; li < 2; ++li) {
        for (int ti = 0; ti < 2; ++ti) apply_cnot(sv, latent[li], trash[ti]);
    }

    return {measure_expZ(sv, 2), measure_expZ(sv, 3)};
}

// Muons block: 4 qubits, particles = mu0, mu1, mu2, mu3
std::array<double, 2> run_mu_block_z(const double x[56]) {
    StateVec<4> sv;
    sv.init_zero();

    for (int k = 0; k < 4; ++k) {
        const ParticleIdx& p = MU_BLOCK_PARTICLES[k];
        double c, s;
        
        // Normalize raw inputs
        double pt_norm = normalize_pt(x[p.pt]);
        double eta_norm = (p.eta >= 0) ? normalize_eta(x[p.eta]) : 0.0;
        double phi_norm = normalize_phi(x[p.phi]);
        
        // RX(eta)
        get_cs(eta_norm, c, s);
        apply_rx(sv, k, c, s);
        
        // RY(pt)
        get_cs(pt_norm, c, s);
        apply_ry(sv, k, c, s);
        
        // RZ(phi)
        get_cs(phi_norm, c, s);
        apply_rz(sv, k, c, s);
    }

    const int latent[2] = {0, 1};
    const int trash[2]  = {2, 3};

    for (int ti = 0; ti < 2; ++ti) {
        for (int li = 0; li < 2; ++li) apply_cnot(sv, trash[ti], latent[li]);
    }

    for (int k = 0; k < 4; ++k) apply_ry(sv, k, mu_weights_c[k], mu_weights_s[k]);

    for (int li = 0; li < 2; ++li) {
        for (int ti = 0; ti < 2; ++ti) apply_cnot(sv, latent[li], trash[ti]);
    }

    return {measure_expZ(sv, 2), measure_expZ(sv, 3)};
}

// Jets block: 10 qubits, particles = e1, j7, j5, e0, MET, mu0, j4, j0, j3, j1
// Jets block: 10 qubits, particles = j0-j9
std::array<double, 4> run_jet_block_z(const double x[56]) {
    StateVec<10> sv;
    sv.init_zero();

    // Feature map on all 10 wires
    for (int k = 0; k < 10; ++k) {
        const ParticleIdx& p = JET_BLOCK_PARTICLES[k];
        double c, s;
        
        // Normalize raw inputs
        double pt_norm = normalize_pt(x[p.pt]);
        double eta_norm = (p.eta >= 0) ? normalize_eta(x[p.eta]) : 0.0;
        double phi_norm = normalize_phi(x[p.phi]);
        
        // RX(eta)
        get_cs(eta_norm, c, s);
        apply_rx(sv, k, c, s);
        
        // RY(pt)
        get_cs(pt_norm, c, s);
        apply_ry(sv, k, c, s);
        
        // RZ(phi)
        get_cs(phi_norm, c, s);
        apply_rz(sv, k, c, s);
    }

    const int latent[6] = {0, 1, 2, 3, 4, 5};
    const int trash[4]  = {6, 7, 8, 9};

    // depth = 4
    for (int d = 0; d < 4; ++d) {
        for (int ti = 0; ti < 4; ++ti) {
            for (int li = 0; li < 6; ++li) apply_cnot(sv, trash[ti], latent[li]);
        }

        int base = d * 10;
        for (int k = 0; k < 10; ++k) {
            apply_ry(sv, k, jet_weights_c[base + k], jet_weights_s[base + k]);
        }

        for (int li = 0; li < 6; ++li) {
            for (int ti = 0; ti < 4; ++ti) apply_cnot(sv, latent[li], trash[ti]);
        }
    }

    return {
        measure_expZ(sv, 6),
        measure_expZ(sv, 7),
        measure_expZ(sv, 8),
        measure_expZ(sv, 9)
    };
}

// -------------------------- Scoring --------------------------
inline double trash_excitation_from_z(double z) {
    return 0.5 * (1.0 - z);
}

struct BlockOutputs {
    double met_z;
    std::array<double,2> ele_z;
    std::array<double,2> mu_z;
    std::array<double,4> jet_z;
};

BlockOutputs run_all_blocks(const double x[56]) {
    BlockOutputs o;
    o.met_z = run_met_block_z(x);
    o.ele_z = run_ele_block_z(x);
    o.mu_z  = run_mu_block_z(x);
    o.jet_z = run_jet_block_z(x);
    return o;
}

std::array<double,4> block_scores_from_outputs(const BlockOutputs& o, const double* presence_mask = nullptr) {
    double met_s = trash_excitation_from_z(o.met_z);

    double ele_s = 0.5 * (
        trash_excitation_from_z(o.ele_z[0]) +
        trash_excitation_from_z(o.ele_z[1])
    );

    double mu_s = 0.5 * (
        trash_excitation_from_z(o.mu_z[0]) +
        trash_excitation_from_z(o.mu_z[1])
    );

    double jet_s = 0.25 * (
        trash_excitation_from_z(o.jet_z[0]) +
        trash_excitation_from_z(o.jet_z[1]) +
        trash_excitation_from_z(o.jet_z[2]) +
        trash_excitation_from_z(o.jet_z[3])
    );

    std::array<double,4> s = {met_s, ele_s, mu_s, jet_s};

    if (presence_mask) {
        for (int i = 0; i < 4; ++i) s[i] *= presence_mask[i];
    }
    return s;
}

double mahalanobis_anomaly_score(const std::array<double,4>& s) {
    double d[4];
    for (int i = 0; i < 4; ++i) d[i] = s[i] - MAHA_MU[i];

    double q = 0.0;
    for (int i = 0; i < 4; ++i) {
        double row = 0.0;
        for (int j = 0; j < 4; ++j) row += MAHA_PREC[i][j] * d[j];
        q += d[i] * row;
    }
    return 0.5 * q;
}

double qae_anomaly_score_ref(const double x[56], const double* presence_mask = nullptr) {
    BlockOutputs bo = run_all_blocks(x);
    auto s = block_scores_from_outputs(bo, presence_mask);
    return mahalanobis_anomaly_score(s);
}

// -------------------------- CSV file reading --------------------------
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <iomanip>

std::vector<std::array<double, 56>> read_csv(const std::string& filename) {
    std::vector<std::array<double, 56>> data;
    std::ifstream file(filename);
    
    if (!file.is_open()) {
        std::cerr << "Error: Could not open " << filename << std::endl;
        return data;
    }
    
    std::string line;
    while (std::getline(file, line)) {
        std::array<double, 56> row;
        std::stringstream ss(line);
        std::string val;
        int col = 0;
        
        while (std::getline(ss, val, ',') && col < 56) {
            row[col++] = std::stod(val);
        }
        
        if (col == 56) {
            data.push_back(row);
        }
    }
    
    return data;
}

void write_scores_csv(const std::string& filename, 
                      const std::vector<std::array<double, 4>>& block_scores,
                      const std::vector<double>& anomaly_scores) {
    std::ofstream file(filename);
    file << std::fixed << std::setprecision(12);
    
    file << "met_score,ele_score,mu_score,jet_score,anomaly_score\n";
    for (size_t i = 0; i < anomaly_scores.size(); ++i) {
        file << block_scores[i][0] << "," 
             << block_scores[i][1] << "," 
             << block_scores[i][2] << "," 
             << block_scores[i][3] << ","
             << anomaly_scores[i] << "\n";
    }
    
    std::cout << "Wrote " << anomaly_scores.size() << " scores to " << filename << std::endl;
}

// -------------------------- Main --------------------------
#include <iomanip>
#include <chrono>

int main(int argc, char* argv[]) {
    std::string input_file = "test_samples.csv";
    std::string output_file = "cpp_scores.csv";
    bool verbose = false;
    
    // Parse command line args
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "-i" && i + 1 < argc) {
            input_file = argv[++i];
        } else if (arg == "-o" && i + 1 < argc) {
            output_file = argv[++i];
        } else if (arg == "-v") {
            verbose = true;
        } else if (arg == "-h" || arg == "--help") {
            std::cout << "Usage: " << argv[0] << " [-i input.csv] [-o output.csv] [-v]\n";
            std::cout << "  -i  Input CSV file with 56 features per row (default: test_samples.csv)\n";
            std::cout << "  -o  Output CSV file for scores (default: cpp_scores.csv)\n";
            std::cout << "  -v  Verbose output (print each sample)\n";
            return 0;
        }
    }
    
    std::cout << "Loading data from " << input_file << "..." << std::endl;
    auto data = read_csv(input_file);
    
    if (data.empty()) {
        std::cerr << "No data loaded. Exiting." << std::endl;
        return 1;
    }
    
    std::cout << "Loaded " << data.size() << " samples" << std::endl;
    
    std::vector<std::array<double, 4>> all_block_scores;
    std::vector<double> all_anomaly_scores;
    all_block_scores.reserve(data.size());
    all_anomaly_scores.reserve(data.size());
    
    auto start = std::chrono::high_resolution_clock::now();
    
    for (size_t i = 0; i < data.size(); ++i) {
        BlockOutputs bo = run_all_blocks(data[i].data());
        auto s = block_scores_from_outputs(bo);
        double score = mahalanobis_anomaly_score(s);
        
        all_block_scores.push_back(s);
        all_anomaly_scores.push_back(score);
        
        if (verbose) {
            std::cout << "Sample " << i << ": "
                      << "block_scores=[" << s[0] << ", " << s[1] << ", " << s[2] << ", " << s[3] << "] "
                      << "anomaly=" << score << std::endl;
        }
    }
    
    auto end = std::chrono::high_resolution_clock::now();
    auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
    
    std::cout << "Inference completed in " << duration.count() << " ms" << std::endl;
    std::cout << "Throughput: " << (data.size() * 1000.0 / duration.count()) << " samples/sec" << std::endl;
    
    // Print summary stats
    double min_score = all_anomaly_scores[0], max_score = all_anomaly_scores[0], sum_score = 0;
    for (double s : all_anomaly_scores) {
        if (s < min_score) min_score = s;
        if (s > max_score) max_score = s;
        sum_score += s;
    }
    double mean_score = sum_score / all_anomaly_scores.size();
    
    std::cout << "\nAnomaly score statistics:" << std::endl;
    std::cout << "  Min:  " << min_score << std::endl;
    std::cout << "  Max:  " << max_score << std::endl;
    std::cout << "  Mean: " << mean_score << std::endl;
    
    // Write output
    write_scores_csv(output_file, all_block_scores, all_anomaly_scores);
    
    return 0;
}
